### ISSUE TITLE
Liste déroulante coupée par le panel

### ISSUE THREAD

**Issue by GtAntoine** [get-focus/deprecated-focus-components-v3#95]
# Current behaviour

Le panel de focus componant coupe la liste déroulante :

![image](https://cloud.githubusercontent.com/assets/8124804/22824502/8431a422-ef88-11e6-96db-eb9be6347895.png)

Pour corriger, virer le  overflow: hidden; dans : 
```css
.mdl-card__supporting-text {
    color: rgba(0,0,0, 0.54);
    font-size: 1rem;
    line-height: 18px;
    overflow: hidden;
    padding: 16px 16px;
    width: 90%;
}
```
## Versions

Focus-components: [3.2.0]
